name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: make 
      run: curl myip.wtf 
      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
